version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
  colorlog:
    class: colorlog.ColoredFormatter
    format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG: 'cyan'
      INFO: 'green'
      WARNING: 'yellow'
      ERROR: 'red'
      CRITICAL: 'bold_red'
handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout
    level: INFO
root:
  handlers: [console]

disable_existing_loggers: false
