# _target_: lightning.Trainer  # Instantiating with hydra.utils.instantiate may pose a security risk

min_epochs: 1 # prevents early stopping
max_epochs: 10

accelerator: cpu
devices: 1
enable_progress_bar: False

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# note needed for single device or cpu training
sync_batchnorm: False
