# training

subset: "default"
train_fraction: 0.8
batch_size_per_gpu: 64
pad: 2000
n_samples_total: 50000

vit_kwargs:
  X_MAX: 3_500
  Y_MAX: 3_500
  Z_MAX: 5_000
  NUM_X_PATCHES: 12
  NUM_Y_PATCHES: 12
  NUM_Z_PATCHES: 12
  NUM_BINS_X_PATCH: 10
  NUM_BINS_Y_PATCH: 10
  NUM_BINS_Z_PATCH: 10
  D_LATENT_SPACE: 512


# tokens
tokens_dir: "/pscratch/sd/r/rmastand/particlemind/tokens/colliderML_parquetfiles"
events_per_tokens_file: 1000
num_tokens_files: 50
batch_size_tokenization: 10

# generated_data
generated_data_dir: "/pscratch/sd/r/rmastand/particlemind/data/generated_colliderML_parquetfiles"
events_per_generated_file: 20
num_generated_files: 1
batch_size_generation: 2


