# training

subsets: ["ttbar_pu0_calo_hits"]
train_fraction: 0.8
batch_size_per_gpu: 4
n_samples_total: 44444
num_workers: 0

system: "HCAL"
data_type: "patch"

vit_kwargs:
  D_EMBEDDING: 32

WANDB_CACHE_DIR: "/scratch/midway3/rmastand/wandb"


# tokens
tokens_dir: "/pscratch/sd/r/rmastand/particlemind/tokens/colliderML_parquetfiles"
events_per_tokens_file: 1000
num_tokens_files: 50
batch_size_tokenization: 10

# generated_data
generated_data_dir: "/pscratch/sd/r/rmastand/particlemind/data/generated_colliderML_parquetfiles"
events_per_generated_file: 20
num_generated_files: 1
batch_size_generation: 2


