trainer_kwargs:
  devices: 4
  accumulate_grad_batches: 128
  max_epochs: 20
  precision: 16
  limit_train_batches: 500
  limit_val_batches: 100


data_kwargs:
  data_dir: "/pscratch/sd/r/rmastand/particlemind/data/p8_ee_tt_ecm365_parquetfiles"
  num_files: 3
  train_fraction: 0.8
  batch_size: 2

model_kwargs:
  input_dim: 4 # DON'T CHANGE
  latent_dim: 16
  hidden_dim: 128
  num_heads: 2
  num_blocks: 2
  alpha: 5
  vq_kwargs: 
    num_codes: 512
    beta: 0.9 
    kmeans_init: True
    norm: null
    cb_norm: null
    affine_lr: 0.0
    sync_nu: 2
    replace_freq: 20
    dim: -1 # DON'T CHANGE


optimizer_kwargs: 
  lr: 0.0001
  weight_decay: 0.01

lr_scheduler_kwargs:
  use_scheduler: True
  warmup_frac: 0.01


    